Rust Port
vanorsigma/neuro-chat-elo pull request #1
Opened 2024-07-05 20:11 UTC by Gaijutsu

This PR aims to port the full functionality of the leaderboard generation to Rust as faithfully as possible. The file layout, type names and structure have been preserved.

There are a few changes of note:
- The python twitch package was replaced with the rust 'twitch_api' crate. This means the badge descriptions are not available. Badge names were substituted for this field.
- The min heap in the copypastaleader metric was replaced with a sorted list, as Rust's BinaryHeap did not fit this application.
- The elo calculation was modified to fit the official approach. This has meant that the leaderboard positions of some chatters has changed in my testing, and the positive elo scores are an order of magnitude smaller.
- Backfilling is now done by setting the 'BACKFILL' env variable. I was unsure of the full usage of 'ACT', however replacing the 'BACKFILL' var in main with 'ACT' could make the process better.

Some extra things are:
- There is now a 'compile-rust' actions workflow so that rust can be compiled without updating the leaderboards

2024-07-07 16:27 UTC, jameshi16 commented
Thanks for the PR!

> The python twitch package was replaced with the rust 'twitch_api' crate. This means the badge descriptions are not available, and so badge names were substituted for this **field**

I've submitted a PR to add titles and descriptions to the badges, so this can be a future todo: https://github.com/twitch-rs/twitch_api/pull/426

> Backfilling is now done by setting the 'BACKFILL' env variable. I was unsure of the full usage of 'ACT', however replacing the 'BACKFILL' var in main with 'ACT' could make the process better.

`ACT` was used for the local Github actions runner: https://github.com/nektos/act. Don't worry about updating it though :)

2024-07-07 16:33 UTC, jameshi16 commented on chatdownloader/src/_types/leaderboardtypes.rs
> +    pub previous_rank: Option<u16>,
can you increase this to u32, and delta to i64 please :pray:

2024-07-07 17:12 UTC, jameshi16 requested changes
thank you for the contribution :)

just some minor comments please

2024-07-07 17:12 UTC, jameshi16 commented on chatdownloader/src/metrics/subs.rs
> +impl Subs {
don't need to have an `impl` when we don't access anything from self. just make it a standalone top-level function and don't export it

2024-07-07 17:12 UTC, jameshi16 commented on chatdownloader/src/metrics/text.rs
> +        Self
btw there are some places where we do `Self {}` and some where we do `Self`. can we standardize?

2024-07-07 17:12 UTC, jameshi16 commented on chatdownloader/src/metrics/text.rs
> +impl Text {
don't need impl, just make it top-level

2024-07-07 17:12 UTC, jameshi16 commented on chatdownloader/src/twitch_utils.rs
> +            .map(ClientId::new)
:+1: good use of functional here, thank you :)

2024-07-07 17:12 UTC, jameshi16 commented on chatdownloader/src/twitch_utils.rs
> +            .build()?;
should expect as well, since if we don't manage to get the http client, we're kinda screwed. maybe do a log first

2024-07-07 17:12 UTC, jameshi16 commented on chatdownloader/src/twitch_utils.rs
> +    pub async fn new() -> Result<Self, reqwest::Error>{
should make it so that if this fails at any point, we'll just expect.

not good practice, but in our case we don't want any chance of continuation

2024-07-07 17:12 UTC, jameshi16 commented on chatdownloader/src/twitch_utils.rs
no dead code?

2024-07-07 17:12 UTC, jameshi16 commented on chatdownloader/src/twitchdownloaderproxy.rs
remove the dead codes, they're not dead

2024-07-07 17:12 UTC, jameshi16 commented on chatdownloader/src/twitchdownloaderproxy.rs
> +        headers.insert("user-agent","CUSTOM_NAME/1.0".parse().unwrap());
probably either omit it (if possible), or define a constant for all user agents used
in `twitch_utils` we used something else

2024-07-07 17:12 UTC, jameshi16 commented on python-chatdownloader/.python-version
?

2024-07-07 17:12 UTC, jameshi16 commented on .github/workflows/trigger-python.yml
can we keep this as `trigger.yml` just because atm the automation script only triggers `trigger.yml`

unless you also want to change [stream_end_listener.py](https://github.com/vanorsigma/neuro-chat-elo/pull/1/files#diff-704ab69bfa4c5f5b05aa4148c16fecc4b55bce523cad6bdd1eaaae269a313cd3)

2024-07-07 17:12 UTC, jameshi16 commented on .github/workflows/backfill-rust.yml
> +        key: ${{ runner.os }}-rust-binary-${{ hashFiles('chatdownloader/Cargo.toml', 'chatdownloader/Cargo.lock') }}
not pushing lock, don't hash on lock

2024-07-07 17:12 UTC, jameshi16 commented on .github/workflows/compile-rust.yml
> +        key: ${{ runner.os }}-rust-binary-${{ hashFiles('chatdownloader/Cargo.toml', 'chatdownloader/Cargo.lock') }}
no lock

2024-07-07 17:12 UTC, jameshi16 commented on .github/workflows/compile-rust.yml
> +        toolchain: stable
actually if possible let's fix this to a version.

we dunno when `stable` is gonna become a major version and stop this from working

2024-07-07 17:27 UTC, Gaijutsu commented on chatdownloader/src/metadata/badges.rs
> +        let user_badges = user_badges.unwrap();
Sure thing. I rewrote it so that shadowing is no longer needed. Hopefully this hasn't compromised readability

2024-07-07 17:34 UTC, Gaijutsu commented on chatdownloader/src/twitch_utils.rs
> +            .map(ClientId::new)
Thank you! :D

2024-07-07 17:39 UTC, Gaijutsu commented on chatdownloader/src/metrics/text.rs
> +        Self
Thanks for catching that

2024-07-07 17:40 UTC, Gaijutsu commented on chatdownloader/src/twitchdownloaderproxy.rs
> +        headers.insert("user-agent","CUSTOM_NAME/1.0".parse().unwrap());
Good idea, I placed the default config in _constants

2024-07-07 17:41 UTC, Gaijutsu commented on chatdownloader/src/twitchdownloaderproxy.rs
But I certainly am

2024-07-07 17:43 UTC, Gaijutsu commented on chatdownloader/src/twitch_utils.rs
> +            .build()?;
Good point

2024-07-07 17:45 UTC, Gaijutsu commented on chatdownloader/src/twitch_utils.rs
> +    pub async fn new() -> Result<Self, reqwest::Error>{
Yep, everything now expects or unwraps

2024-07-07 17:45 UTC, Gaijutsu commented on chatdownloader/src/metrics/metrictrait.rs
> +    fn get_name(&self) -> String;
Good catch, everything is String now

2024-07-07 17:46 UTC, Gaijutsu commented on chatdownloader/src/leaderboards/nonvips.rs
> +        if performance.metadata.contains_key("special_role") && *performance.metadata.get("special_role").unwrap().get_bool().unwrap() {
Done!

2024-07-07 17:46 UTC, Gaijutsu commented on chatdownloader/src/_types/twitchtypes.rs
> +    pub bits_spent: Option<u32>,
Erm, it never was. Just Schizo fr fr

2024-07-07 17:47 UTC, Gaijutsu commented on .github/workflows/compile-rust.yml
> +        toolchain: stable
Sounds good, just locked it to the current version

2024-07-07 17:47 UTC, Gaijutsu commented on chatdownloader/src/_types/leaderboardtypes.rs
> +    pub previous_rank: Option<u16>,
Done!

2024-07-07 17:48 UTC, Gaijutsu commented on chatdownloader/src/metrics/subs.rs
> +impl Subs {
Good point, done

2024-07-07 17:53 UTC, Gaijutsu commented on chatdownloader/src/backfill.rs
> +        let processor = ChatLogProcessor::new(twitch.clone());
Good idea, I've implemented the change

2024-07-07 17:54 UTC, Gaijutsu commented on .github/workflows/compile-rust.yml
> +        toolchain: stable
Good point. I've fixed the version to the current rust version

2024-07-08 21:36 UTC, closed without merging

2024-07-08 21:54 UTC, jameshi16 commented
(sorry, I did a history re-write, so you'll probably have to cherry-pick [97ad1c6](https://github.com/vanorsigma/neuro-chat-elo/pull/1/commits/97ad1c6fa1354476a5f1474a0411659da210fb42) to [ede0652](https://github.com/vanorsigma/neuro-chat-elo/pull/1/commits/ede06528d486a89c8fb60d8af220a5cdc3db058a)