Fix percentile function
vanorsigma/neuro-chat-elo pull request #11
Opened 2024-08-06 01:09 UTC by Gaijutsu

Adds an empty list guard to the  ```percentile``` function of leaderboard trait.

2024-08-06 07:08 UTC, jameshi16 commented
redelegating to @owobred because i believe they're also looking at this

2024-08-06 08:44 UTC, jameshi16 commented
❗ : based on our future goals, please address that panic (replace it with a helpful log, please) and save an empty leaderboard instead.

2024-08-06 08:44 UTC, jameshi16 requested changes
see comment above

2024-08-07 13:43 UTC, jameshi16 approved these changes

2024-08-07 13:45 UTC, Gaijutsu commented
Thanks for the reviews! I'll go ahead and merge.

2024-08-07 13:45 UTC, merged