Protobuf Leaderboard Storage
vanorsigma/neuro-chat-elo pull request #15
Opened 2024-08-09 22:52 UTC by Gaijutsu

# Changes

This PR moves leaderboards from JSON to Google's Protobuf format 

## Related Cards

- https://github.com/orgs/vanorsigma/projects/1?pane=issue&itemId=67134218

2024-08-10 08:25 UTC, jameshi16 commented
Could you post some performance metrics? E.g. how much space is saved

2024-08-10 15:55 UTC, Gaijutsu commented
Sure thing, probably should have been in the original PR :laughing: 

![Leaderboard Access Time](https://github.com/user-attachments/assets/7510f075-6de6-4f88-ba56-61a81fe65a3a)
The above is accessing files in a single run, averaged across several runs.

![Leaderboard File Space](https://github.com/user-attachments/assets/9813e818-39b5-4fe8-8d4d-f06defa2ab5f)
The above is file size after running a full backfill

All tests were performed on my home desktop

2024-08-12 09:04 UTC, jameshi16 requested changes
Thanks for looking into this. Please see the comments

2024-08-12 09:04 UTC, jameshi16 commented on web/src/lib/ranks.ts
> +          const LeaderboardExport = root.lookupType("leaderboard.LeaderboardExport");
This doesn't look too amazing, because there isn't an associated type in TypeScript lang that I can rely on. Please look for an alternative if they exist

2024-08-12 09:04 UTC, jameshi16 commented on web/src/lib/ranks.ts
> +          console.error('Protobuf decoding error:', err);
Make this an alert & add a TODO for a proper error handling page. A failed leaderboard load should completely halt the user experience

2024-08-12 09:04 UTC, jameshi16 commented on web/src/lib/ranks.ts
> +          set(object.items as any);
From https://github.com/protobufjs/protobuf.js?tab=readme-ov-file#toolset:

> Message.create(properties: Object): Message
creates a new message instance from a set of properties that satisfy the requirements of a valid message. Where applicable, **_it is recommended to prefer Message.create over Message.fromObject_** because it doesn't perform possibly redundant conversion.

Please do the needful

2024-08-12 19:27 UTC, Gaijutsu commented on web/src/lib/ranks.ts
> +          const LeaderboardExport = root.lookupType("leaderboard.LeaderboardExport");
Sure thing. I moved to ts-proto to compile ts classes and decoders, so Protobuf is now decoded into strict TS interfaces.

2024-08-13 11:20 UTC, jameshi16 requested changes
Thank you, still requires a little bit more work 🙏

2024-08-13 11:20 UTC, jameshi16 commented on web/src/lib/ranks.ts
> +            }
This function is super long, can we break it up into a bunch of functions please. Something like `fromProtoBadgesToBadges`, `fromProtoRankingToRanking`, etc. (Don't use these names they're terrible, but you get the point I hope)

Also use `.map`, they exist in JS too!

2024-08-13 11:23 UTC, jameshi16 commented
+ do adjust `package.json` to add a target to generate models

2024-08-13 15:28 UTC, Gaijutsu commented on rust/elo/src/_types/leaderboardtypes.rs
> +    pub badges: prost::alloc::vec::Vec<BadgeInformation>,
I previously had a version working with prost-build which I can reintroduce. Would protobuf-codegen be preferable?

2024-08-14 10:40 UTC, jameshi16 requested changes
Thank you, mostly happy with this. Just some more minor changes and I think we're good.

In general, we should think about the developer experience when they clone the repository. For rust, I believe `rust-analyzer` will automatically try to build the repo and create the generated files, so that's fine. For typescript, it doesn't do that automatically, so devs will have a degraded experience if they've not run `npm run build` at least once.

We should either add instructions to properly setup the repository, or a `setup.sh` script or similar for new devs to easily setup their environment.

2024-08-14 10:40 UTC, jameshi16 commented on rust/elo/src/_types/leaderboardtypes.rs
> +// Both below types are defined in above protobuf file
This comment is something we'll have to maintain if we add a new type to the `.proto` file. I think it's not necessary to have this if we already have Line 5

2024-08-14 10:40 UTC, jameshi16 commented on rust/elo/src/_types/leaderboardtypes.rs
> +            score: 1200.0,
Unluckily for us, `LeaderboardExportItem` is not a superset of `LeaderbordInnerState`. We can provide a helper method, but I don't think it can be a `From`.

2024-08-14 10:40 UTC, jameshi16 commented on rust/elo/src/leaderboards/leaderboardtrait.rs
> +        msg.encode(&mut buf).unwrap();
https://docs.rs/prost/latest/prost/trait.Message.html#method.encode_to_vec

2024-08-14 10:40 UTC, jameshi16 commented on rust/elo/src/leaderboards/leaderboardtrait.rs
> +        file.write_all(&buf).unwrap();
np: one-liner possible

2024-08-14 10:40 UTC, jameshi16 commented on rust/elo/src/metadata/badges.rs
> +use crate::_types::leaderboardtypes::BadgeInformation;
?: can be combined:
```rust
use crate::_types::{clptypes::{...}, leaderboardtypes::{...}}
```

unless this is what `rust-fmt` / clippy did. do let me know

2024-08-14 10:40 UTC, jameshi16 commented on web/package.json
>      "build": "vite build",
```suggestion
    "build": "npm run compileProtos && vite build",
```

2024-08-14 10:40 UTC, jameshi16 commented on web/package.json
> +    "compileProtos": "protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=./src/gen/ --proto_path=../models/ ../models/leaderboardExportTypes.proto",
Can we do something like
```
protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=./src/gen/ --proto_path=../models/ ../models/*.proto
```

to get free future-proofing?

2024-08-14 10:40 UTC, jameshi16 commented on web/src/gen/leaderboardExportTypes.ts
Since we're not checking in the types for the Rust crate, it doesn't make sense to check-in the types for TS too. (Choose one of the two to do)

Can you update `.gitignore` and `README.md` to force developers to run `npm run build` (or `npm run compileProtos`, whichever) the first time they clone the project?

2024-08-19 15:08 UTC, jameshi16 approved these changes
lgtm, np: also add instructions to install `protoc`?

2024-08-19 21:01 UTC, merged