Leaderboard Opt Out
vanorsigma/neuro-chat-elo pull request #16
Opened 2024-08-11 23:27 UTC by Gaijutsu

# Changes
This PR adds Discord and Twitch Whispers bots to allow users to opt out and back in to the respective leaderboards. These requests are stored in a Firestore database, and downloaded en masse when leaderboard processing begins. 

## To-do List

- [x] Create discord and twitch bots
- [x] Exclude opted out users from processing
- [ ] Drop opted out users from previous leaderboards

## Related Cards
- https://github.com/orgs/vanorsigma/projects/1/views/1?pane=issue&itemId=72551263

2024-08-12 08:47 UTC, jameshi16 requested changes
- [ ] Add typings to all Python script introduced, or consider another language
- [ ] Do not hard-code any URLs. Introduce some sort of config. If we need another task for this, please create one. The config should now encapsulate all hard-coded things we have in the project
- [ ] Injecting the `optout_list` into every leaderboard via `new()` seems like a code stink to me. Why are we opting out at a per-leaderboard level, and not at a global level? (Maybe implement in abstract leaderboards? Also, please make `optout_list` injectable. So, implement a default `optout_list` that is just empty, and inject it via `set_optout_list`. Makes it testable in the future.)

2024-08-12 11:16 UTC, jameshi16 commented
> I'm not really sure what the best way to put this idea forward is, but couldn't this be done entirely on cloudflare workers instead of having to host a discord + twitch bot 24/7? i.e. twitch provides [a whisper event](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#userwhispermessage) (from what I can tell you're consuming it over websocket) than can be observed over webhooks, and discord provides [interactions](https://discord.com/developers/docs/interactions/overview) which also work over webhooks. I'm willing to attempt this in a seperate PR instead of pushing this onto you, as I get this is a bit out of the blue.
> 
> I'm not too sure how I feel about removing users at the leaderboard processing stage, wouldn't it make more sense to prune them in [`MessageProcessor::process_message`](https://github.com/vanorsigma/neuro-chat-elo/blob/main/rust/elo/src/lib.rs#L51)?

I also thought about this while reviewing (where pruning takes place). It make sense because we also have to remove opted out users who have already made it into previous leaderboards.

Was thinking if we could just prune at leaderboards, but then live elo would leak elo updates without a prune at that stage.

Not sure if there's a cleaner design for this atm

2024-08-12 16:11 UTC, Gaijutsu commented
I wasn't happy with where this PR was, but wasn't sure the best way to ask for suggestions outside of creating it. Sorry about that and thank you for the notes! :pray: PS. how should I do this in future?

I think @owobred's idea sounds great, and I'm happy to give that a go unless you think it's best you take over. 

As for how to actually implement optouts on the rust side, I'll put some more thought into doing it cleanly, but I'm not sure we can avoid checking in two places. I'll think on it some more.

I'm making this PR into a draft while I rewrite for cloudflare and address the other changes.

2024-08-12 17:21 UTC, Gaijutsu commented
Thanks for this, probably saved me a lot of time! I'll give this a go after I do cleanup on  protobuf leaderboards.

Sorry again for the bad PR 🙏

2024-08-12 23:29 UTC, Gaijutsu commented
This first version leaves most of owobred's stuff unchanged, but processes commands and integrates with the existing Firestore.

Of note is it seems like firebase-admin will not work on Cloudflare Workers. I have since found https://github.com/samuelgozi/firebase-firestore-lite, but by that time I had already implemented the functionality with REST API calls. I'm happy to make the switch though.

In its current state the Worker can take !optout and !optin via Twitch Whispers and add / remove from the Firestore as appropriate, however it cannot send Whispers back yet.

2024-08-17 00:22 UTC, Gaijutsu commented
Alright, I believe the Cloudflare Worker and setup are now feature complete. As for the Rust side, I'm still not sure of a good way to do it. 

Abstract leaderboard has a function called `cull_ids`, which is now run after they are instantiated. The `optout.rs`  is left largely unchanged. The IDs are removed in two places, at message processing, and after leaderboards are instantiated.

2024-08-19 15:09 UTC, jameshi16 commented
this one needs a rebase too @Gaijutsu

2024-08-19 15:11 UTC, Gaijutsu commented
Incredible timing :clueless:

2024-08-20 11:39 UTC, jameshi16 requested changes
Thanks for the work!

2024-08-20 11:39 UTC, jameshi16 commented on optout/optout-worker/src/twitch.ts
> +            }
same deal here

2024-08-20 11:39 UTC, jameshi16 commented on optout/optout-worker/src/twitch.ts
> +}
is there a library to do this? ideally we shouldn't be doing our own signature verification. the lowest level we should go is to call `getHmac` from a library or something

2024-08-20 11:39 UTC, jameshi16 commented on optout/optout-worker/src/twitch.ts
> +    }
can this be moved outside of `twitch.ts`?

2024-08-20 11:39 UTC, jameshi16 commented on optout/optout-worker/test/index.spec.ts
if we're not testing anything, please remove this

2024-08-20 11:39 UTC, jameshi16 commented on optout/optout-worker/wrangler.toml
> +DISCORD_PUBLIC_KEY = "60d23e01987f1991fbbecc5a987a7447f9f7b4b96ea156c14270e0c52b8b7c3d"
is there a way to _not_ have this in `wrangler.toml`?

2024-08-20 11:39 UTC, jameshi16 commented on rust/chatdownloader/src/backfill.rs
> +use crate::chatlogprocessor::{self, ChatLogProcessor};
why both `self` and `ChatLogProcessor`?

2024-08-20 11:39 UTC, jameshi16 commented on rust/chatdownloader/src/chatlogprocessor.rs
> +impl<'a> ChatLogProcessor<'a> {
is there a way to do it without introducing lifetimes?

2024-08-20 11:39 UTC, jameshi16 commented on rust/chatdownloader/src/chatlogprocessor.rs
> +                .map(|comment| Message::from(comment)),
Does this need to be like this?

2024-08-20 11:39 UTC, jameshi16 commented on rust/chatdownloader/src/chatlogprocessor.rs
> +                debug!("Skipping opted out user for message: {:#?}", message);
maybe only print the username?

2024-08-20 11:39 UTC, jameshi16 commented on rust/chatdownloader/src/chatlogprocessor.rs
> +            LeaderboardProcessor::new(&optout_manager.twitch_ids, &optout_manager.discord_ids);
Can we use an enum to differentiate between the two enums, and pass only one parameter here? It'll be troublesome if we need to extend opt-out functionality to other platforms

2024-08-20 11:39 UTC, jameshi16 commented on rust/elo/src/leaderboards/mod.rs
> +        cull_leaderboards!(discord_ids, discordlivestreamchat);
I feel like we should filter at save-time rather than culling it at load-time.

Thinking from the perspective of `live-elo`. Live Elo loads the leaderboard once at the very start of the program, and keeps leaderboard state in memory until it is killed. Every so often it will dump a final state leaderboard.

If we receive an opt-out in the middle of the stream, this logic will not be able to remove people who are already on the in-memory leaderboard; they'll just not get any elo updates.

@owobred if you have any inputs, please do let me know

2024-08-20 11:39 UTC, jameshi16 commented on rust/chatdownloader/src/main.rs
> +        .refresh_optouts()
Is it the intention to refresh optouts every once in a while? Has the design considered if this is possible?

@owobred, do you reckon optout manager will have to live in an `Arc<>`, and used everywhere?

In that case, can we do something equivalent to an `AppState` that is injected to all dependencies? So `AppState` will have to contain both the Twitch client and the optout manager.

2024-08-20 11:39 UTC, jameshi16 commented on rust/optout/src/lib.rs
> +            .get("https://firestore.googleapis.com/v1/projects/neuro-chat-elo/databases/(default)/documents/opt_outs/")
all hardcoded strings need a constant

2024-08-20 11:56 UTC, Gaijutsu commented on optout/optout-setup/twitch_setup.py
> +        log.debug(twitch._user_auth_token)
I left it in for debugging, guess I never removed it extremelyoblivious

2024-08-20 12:12 UTC, jameshi16 commented on optout/optout-setup/twitch_setup.py
> +        token, refresh_token = await auth.authenticate(browser_new=1)
i see, i did assume this was a one-shot script the dev has to run to "prime" vars.

ideally, if possible, i don't want the script to launch a browser - imo it's doing too much. if it's not possible, let me know @Gaijutsu

(i looked at the `authenticate` code for 2.1 seconds, i _think_ you can implement a "custom browser" that just prints the url in the terminal)

2024-08-20 12:13 UTC, jameshi16 commented on rust/elo/src/leaderboards/mod.rs
> +        cull_leaderboards!(discord_ids, discordlivestreamchat);
Additionally I think a Decorator pattern might work really well here

2024-08-20 14:02 UTC, Gaijutsu commented on rust/chatdownloader/src/backfill.rs
> +use crate::chatlogprocessor::{self, ChatLogProcessor};
Because vscode is strange sometimes ¯\\_(ツ)_/¯

2024-08-20 14:02 UTC, Gaijutsu commented on rust/chatdownloader/src/chatlogprocessor.rs
> +                .map(|comment| Message::from(comment)),
Nah, it's a merge artifact

2024-08-22 22:37 UTC, closed without merging

2024-08-22 22:37 UTC, Gaijutsu commented
Given the gigantic size of this PR and the upcoming Rust changes, I will be closing this PR and splitting it into 3. One for each of the Twitch Bot, Discord Bot and Rust. I'll do my best to address all of the requested changes for each respective section before making the first PR.