Moving Emote Processing into SevenTVClient
vanorsigma/neuro-chat-elo pull request #20
Opened 2024-08-22 20:20 UTC by Gaijutsu

# Changes

This PR prepares for the implementation of a most used emote leaderboard. Access to 7TV emotes and functions related to them will be required by 2 metrics (includes the existing emotes metric) and 1 metadata. 

As such, this PR moves 7TV into its own struct in the `twitch_utils` crate. The struct lives in an Arc reference which will be cloned and passed to all services that need it.

## Related Cards

- https://github.com/orgs/vanorsigma/projects/1/views/1?pane=issue&itemId=76010173

2024-08-23 18:04 UTC, jameshi16 requested changes
some changes

2024-08-23 18:04 UTC, jameshi16 commented on rust/twitch_utils/src/seventvclient.rs
> +        emotes
```suggestion
self.get_7tv_emotes_in_fragment(fragment)
            .iter()
            .map(|emote| TwitchEmote::from(emote.clone()))
            .chain(fragment.emoticon.iter().map(|s| {
                TwitchEmote::from_twitch_name_id(fragment.text.clone(), s.emoticon_id.clone())
            }))
            .collect()
```

2024-08-23 18:04 UTC, jameshi16 commented on rust/twitch_utils/src/twitchtypes.rs
> +}
`&` to owned object by cloning everything seems strange to me, we may as well force the caller to `.clone()` before converting it to `TwitchEmote`

2024-08-23 21:34 UTC, Gaijutsu commented on rust/elo/src/metrics/mod.rs
> +        let mut emote = emote::Emote::new().await;
Interesting side effect of this PR is that metric constructors are no longer async

2024-08-25 08:34 UTC, jameshi16 commented
![image](https://github.com/user-attachments/assets/49538752-048e-4dc5-8f48-71f3745189c3)
![4x](https://github.com/user-attachments/assets/31a747c0-89fd-422a-843e-df49ef027b35)

2024-08-25 08:37 UTC, jameshi16 approved these changes
(lgtm)

2024-08-25 11:34 UTC, merged