Twitch Optout Bot
vanorsigma/neuro-chat-elo pull request #21
Opened 2024-08-23 01:09 UTC by Gaijutsu

# Changes

This PR introduces a Cloudflare Worker based Twitch Whispers bot for processing opt-out and opt-in requests. These requests are stored in a Firestore database for later retrieval.

Also introduced is a python based setup script, which is to be run when the worker is deployed for the first time. Instructions for how to setup the worker using this script are in the README.md at the root of optout.

## Related Cards

- https://github.com/orgs/vanorsigma/projects/1?pane=issue&itemId=72551263

2024-08-25 08:59 UTC, jameshi16 requested changes
some questions

@owobred, do give it a review asw since you should have more context then I do

2024-08-25 08:59 UTC, jameshi16 commented on optout/optout-worker/src/firebase.ts
Can I confirm that there are no firebase libraries for typescript?

2024-08-25 08:59 UTC, jameshi16 commented on optout/optout-worker/src/index.ts
> +} satisfies ExportedHandler<Env>;
?: Why is this line needed?

2024-08-25 08:59 UTC, jameshi16 commented on optout/optout-worker/src/twitch.ts
> +// TODO: Add proper error handling
Put this out in a card and remove it

2024-08-25 08:59 UTC, jameshi16 commented on optout/optout-worker/src/twitch.ts
To be perfectly honest, I still think this is quite icky. Can we confirm that there are no twitch libraries we can use? (It looks like we're using the proper OAuth workflow here, but I could be wrong)

2024-08-25 12:02 UTC, Gaijutsu commented on optout/optout-setup/pyproject.toml
> +authors = ["Gaijutsu", "owobred"]
Looks like it's optional, so I'll just drop it :+1:

2024-08-25 12:25 UTC, Gaijutsu commented on optout/optout-worker/src/twitch.ts
I'll give libraries another try now that I know how Cloudflare does its node compatibility stuffs :+1:

2024-08-25 12:47 UTC, Gaijutsu commented on optout/optout-worker/src/firebase.ts
Took another run at it, and  found the `fireworkers` library to work perfectly

2024-08-25 12:48 UTC, Gaijutsu commented on optout/optout-worker/src/twitch.ts
> +            return new Response('Who asked lol');
Very good point, I've added some help text to the default text.

2024-11-06 18:08 UTC, AlsoGaijutsu commented
Closing as this is now too far out of date

2024-11-06 18:08 UTC, closed without merging