Remove the constructor from MetadataTrait
vanorsigma/neuro-chat-elo pull request #25
Opened 2024-08-27 02:37 UTC by Gaijutsu

# Changes

This PR moves the constructor for metadata structs out of `AbstractMetadata` and into each structs' implementation. This is to support the injection of either `SevenTVClient` or `TwitchAPIWrapper` following the advice for #20.

I've left all constuctors as async, however only one metadata (`badges`) needs to be async. Is it better to maintain uniformity and keep everything async, or have the other constructors be non-async?

## Related Cards

- https://github.com/orgs/vanorsigma/projects/1?pane=issue&itemId=76010173

2024-08-27 06:46 UTC, jameshi16 approved these changes
LGTM

2024-08-27 11:57 UTC, Gaijutsu commented
I kept everything async, so reintroduced the awaits. One last check?

2024-08-27 12:08 UTC, jameshi16 requested changes
Sorry, I didn't expect to need to check for correctness because I assumed that the committer checked at least once. Checking if the code is correct puts too much stress on the reviewer, especially for a relatively large-sized repo with only 3 contributors. Typically, we would be confident that a change is correct via unit tests and a build process, both of which the repo currently lacks (for good reason, we just don't have the time atm)

It would be nice to have a build process that does this automatically for us, but I'll hold off implementing it until live elo is ready. For now I'll probably update the PR template.

As for the async `new()`, if they can be sync, make them sync, because I reckon the overhead to make them async will outweigh just allocating the objects directly.

2024-08-27 12:10 UTC, jameshi16 commented
This is a systematic issue that caused #24 as well. I'll do better, my apologies

2024-08-27 12:29 UTC, Gaijutsu commented
Both of these issues are entirely my fault, and are entirely because I was careless when submitting changes. I sincerely apologise for this. You are right that reviewers shouldn't have the responsibility of checking correctness as well, that it is my responsibility as the one making the PR to have checked, and that I failed to do that. 

I'll be changing this behaviour for PRs going forward, and I'm truly sorry to have caused this trouble.

2024-08-27 12:43 UTC, jameshi16 commented
I doubt it is your fault. This is clearly a systematic issue (we don't have the infrastructure to prevent this from happening), which falls under my responsibility as the repo owner. Don't worry too much about it.

2024-08-28 10:57 UTC, jameshi16 approved these changes
lgtm

2024-08-28 12:45 UTC, merged