Top Emotes Leaderboard
vanorsigma/neuro-chat-elo pull request #28
Opened 2024-08-28 14:06 UTC by Gaijutsu

# Changes

This PR contains three units of change. 
- Creation of a new `MessageTag` called `Emote` and integration with the `ChatOrigin` metadata
- Extraction of emote `BasicInfo` in `basic_info.rs`
- The `top-emote` leaderboard with its associated `emote-use` metric

`ChatOrigin` will now output a `MetadataUpdate` that contains both the `MessageTag` for the `userId`, as well as for all of the emotes in their Message. The Emote `MessageTag` is constructed by passing the emote to `MessageTage::from`, with plans to eventually support discord emotes.

The `BasicInfo` metadata processor now produces `BasicInfo` metadata types for both the user, and all emotes in their Message.

The `top-emote` leaderboard tracks emote use with the `emote-use` metric. The metric adds one score to an emote whenever it appears in a message.

## Checklist

- [x] My code compiles
- [x] I have committed all the files needed to build the project (check if your file is found in `.gitignore`)
- [x] If I'm introducing a new step in the build process, I have documented / automated it
- [x] I have tested my changes (minimally with one Twitch VOD)

## Related Cards

- https://github.com/orgs/vanorsigma/projects/1?pane=issue&itemId=76010173

2024-08-30 09:22 UTC, jameshi16 requested changes
Thanks, just a bunch of nitpicks and general query. Also a blocking change for ID since the IDs are shifted by one in the actual deployment.

2024-08-30 09:22 UTC, jameshi16 commented on rust/twitch_utils/src/twitchtypes.rs
> +            }
qns: were there any cases where this is needed?

2024-08-30 09:22 UTC, jameshi16 commented on rust/elo/src/metadata/basic_info.rs
> +                .iter()
np: maybe into_iter makes more sense here

2024-08-30 09:22 UTC, jameshi16 commented on rust/elo/src/metrics/emoteuse.rs
> +                    });
np: is there a more functional way to do this? maybe try to do a `reduce` with the starting value being `HashMap::new()`?

2024-08-30 09:22 UTC, jameshi16 commented on web/src/lib/menu.svelte
> +    'Top Emotes': 8
sorry could this be set to 9 instead

2024-08-30 15:54 UTC, Gaijutsu commented on rust/twitch_utils/src/twitchtypes.rs
> +            }
I've never seen it happen. Do you think we should throw an error if this happens?

2024-09-02 12:34 UTC, jameshi16 requested changes

2024-09-02 12:34 UTC, jameshi16 commented on rust/elo/src/_types/clptypes.rs
> +        }
Is this needed? We're supposed to have a wrapper around `TwitchEmote`, and that wrapper should be consuming `TwitchEmote`. Should have been covered by `impl From<$raw_message> for Message {` above. Any reason why `TwitchEmote` needs a special implementation?

2024-09-02 12:34 UTC, jameshi16 commented on rust/elo/src/_types/clptypes.rs
> +    (TwitchEmote, TwitchEmote)
I didn't catch this before, but I did now. Can the left and right of the tuple have different names? The left should be wrapping the right.

2024-09-02 12:34 UTC, jameshi16 commented on rust/twitch_utils/src/twitchtypes.rs
> +            }
Why doesn't the old method work?

2024-09-02 13:00 UTC, Gaijutsu commented on rust/twitch_utils/src/twitchtypes.rs
> +            }
The old method grabbed the root url for the emote, which can't be used to directly display the emote. This final step of adding the specific image was elsewhere before this branch was split for PRs, but now I think it's most appropriate here.

2024-09-02 13:42 UTC, Gaijutsu commented on rust/elo/src/_types/clptypes.rs
> +        }
It felt wrong having to do TwitchEmote -> Message since TwitchEmotes aren't messages, but I'm happy to have it follow the standard implementation.

2024-09-02 14:09 UTC, jameshi16 commented on rust/elo/src/_types/clptypes.rs
> +        }
Following that logic, it wouldn't make sense associating `MessageTag` to `TwitchEmote` in the first place 😅

2024-09-02 15:03 UTC, Gaijutsu commented on rust/elo/src/_types/clptypes.rs
> +        }
It doesn't really, but unless we want to rename MessageTags it's what we have to use ¯\\_(ツ)_/¯

2024-09-02 15:20 UTC, jameshi16 commented on rust/elo/src/_types/clptypes.rs
> +        }
I think we may have a different interpretation of what counts as a message.

As far as I understand, a message is not necessarily a chat message. It's just literally a message from an origin. If anything, the more misleading name is `ChatOrigin`, since it's not necessarily the case that our messages come from chat.

Is there something I can do to clarify this point in the codebase?

2024-09-02 15:23 UTC, jameshi16 commented on rust/twitch_utils/src/twitchtypes.rs
> +            }
Oh, so was the old PR not fully functional, then? Seems like something that escaped my review again, lol...

2024-09-02 15:30 UTC, jameshi16 approved these changes
LGTM.

Might need to create a card to rename `ChatOrigin` and `ChatLogProcessor` to be more precise about what we're achieving.

Maybe we'll name it correctly in live-elo

2024-09-02 15:54 UTC, Gaijutsu commented on rust/elo/src/_types/clptypes.rs
> +        }
Yeah, my confusion came from the concept of chat messages, and it being used in `ChatOrigin`. I think it would be for the best to rename `ChatOrigin` to prevent this this sort of thing. :laughing:

2024-09-03 00:23 UTC, merged