[FEAT] Rust Parallel Processing
vanorsigma/neuro-chat-elo pull request #3
Opened 2024-07-12 16:59 UTC by Gaijutsu

This PR aims to introduce parallelism for metrics, metadata, and leaderboard updates.

This involved a serious refactor of chatlogprocessor.rs and the mod.rs files of metrics, metadata, and leaderboards.

The main structure is:
- Threads are spawned to handle each of the metrics and metadata
- A thread is spawned to use a tokio broadcast channel to send comments to the metric and metadata threads
(This does not need to be its own thread for the current state, but might be helpful if you plan to support updating the leaderboard during an ongoing stream) 
- The metric and metadata threads use an mpsc channel to send their outputs to a thread that manages UserChatPerformances
- The UserChatPerformance thread joins to produce the full vector of performances
- The performances are broadcasted to threads that each manage a leaderboard for updating and saving

This PR also includes a partial refactor of some files to make better use of functional programming, as well as a run of ```cargo fmt```

2024-07-15 08:22 UTC, jameshi16 requested changes
thank you very epic

2024-07-15 08:22 UTC, jameshi16 commented on chatdownloader/src/chatlogprocessor.rs
> +            };
If we're not doing anything for the `Ok(_)` branch, can we use a `if let Err` here?

2024-07-15 08:22 UTC, jameshi16 commented on chatdownloader/src/chatlogprocessor.rs
> +}
ok hear me out, most of these functions don't need to be threads.

most of them can just be `async fn`, with some cheeky usages of `yield_now` here: https://recursion.wtf/tracing-honeycomb/tokio/task/fn.yield_now.html

all we really need to do is a `join!` on everything later on. try it out and let me know if there are any troubles

2024-07-15 08:22 UTC, jameshi16 commented on chatdownloader/src/chatlogprocessor.rs
> +                                *metadata_value = met_value.clone();
why is .clone() needed here? in line 120 there wasn't a clone

2024-07-15 08:22 UTC, jameshi16 commented on chatdownloader/src/chatlogprocessor.rs
> +                                    None => {warn!("Could not get username and/or url"); ("".to_string(), "".to_string())}
ideally if this happens we shouldn't even update `user_chat_performance`. it'll be quite catastrophic if there is an empty username on the leaderboard

2024-07-15 08:22 UTC, jameshi16 commented on chatdownloader/src/chatlogprocessor.rs
> +            username: "".to_string(),
i don't like this. will it be hard to make username `user_id` by default?

2024-07-15 08:22 UTC, jameshi16 commented on chatdownloader/src/leaderboards/leaderboardtrait.rs
> +        (0..step_count)
i _believe_ you can use chunks here instead: https://doc.rust-lang.org/std/slice/struct.Chunks.html

2024-07-15 08:22 UTC, jameshi16 commented on chatdownloader/src/leaderboards/mod.rs
> +pub fn get_leaderboards() -> (
can you check the possibility of using just async functions with some uses of yield_now?

2024-07-15 08:22 UTC, jameshi16 commented on chatdownloader/src/metadata/mod.rs
> +fn spawn_thread<M>(
(same comment as metrics)

2024-07-15 08:22 UTC, jameshi16 commented on chatdownloader/src/metadata/mod.rs
> +    let (broadcast_sender, broadcast_receiver) = broadcast::channel(100000);
pls use a const here

2024-07-15 08:22 UTC, jameshi16 commented on chatdownloader/src/metrics/copypastaleader.rs
> +            ));
refactor this, I think you can do something like

```rust
let parent_sequence = if best_match_score > MATCHING_THRESHOLD {
    best_match.3
} else {
    sequence_no
}

self.history.push((sequence_no, text.clone(), comment.commenter._id.clone(), parent_sequence))
```

2024-07-15 08:22 UTC, jameshi16 commented on chatdownloader/src/metrics/copypastaleader.rs
> +fn lcs(s1: &str, s2: &str) -> String {
i don't remember how to lcs so i'm assuming this is right extremelyoblivious

2024-07-15 08:22 UTC, jameshi16 commented on chatdownloader/src/metrics/mod.rs
> +fn spawn_thread<M>(
hello pls try to see if you can mix `async move` with enough `yield_now` to remove the need for async. the rule of thumb is, if you are `send` or `recv`, and they can't be async, add a `yield_now().await` after the `send`/`recv`.

2024-07-15 15:17 UTC, Gaijutsu commented on chatdownloader/src/chatlogprocessor.rs
> +                                    None => {warn!("Could not get username and/or url"); ("".to_string(), "".to_string())}
Good point. I made the warning more specific and had it move to the next performance instead

2024-07-17 17:47 UTC, Gaijutsu commented on chatdownloader/src/chatlogprocessor.rs
> +            };
Yep!

2024-07-19 23:10 UTC, Gaijutsu commented on chatdownloader/src/metrics/mod.rs
> +fn spawn_thread<M>(
This is a fantastic point, and halved the processing time. Thank you! :+1:

2024-07-19 23:10 UTC, Gaijutsu commented on chatdownloader/src/chatlogprocessor.rs
> +pub fn spawn_user_chat_perforance_thread(
Thanks lol, good catch.

2024-07-21 16:10 UTC, jameshi16 requested changes
thank you for the revision, but please minimally address the blocking comments

2024-07-21 16:10 UTC, jameshi16 commented on chatdownloader/src/leaderboards/leaderboardtrait.rs
> +            .collect();
np: this looks insanely messy to me, in fact the previous changes looks better. i think we can still do functional here, probably with some combination of `min_by_key` or something. can you refactor this?

2024-07-21 16:10 UTC, jameshi16 commented on chatdownloader/src/metadata/mod.rs
> +            mpsc_sender: None,
blocking: i think there's better design than to set these to `None`. We lose the ability to check this at compile time, and have to panic otherwise.

based on the usage, we always use `new` with `get_defaults_and_setup_channels`. is it possible for `get_defaults_and_setup_channels` to return this object instead?

2024-07-21 16:10 UTC, jameshi16 commented on chatdownloader/src/metadata/mod.rs
> +        self.mpsc_sender.replace(mpsc_sender);
see above comment

2024-07-21 16:10 UTC, jameshi16 commented on chatdownloader/src/metadata/mod.rs
> +        };
if the blocking comment cannot be addressed, please address this instead @Gaijutsu

2024-07-21 16:10 UTC, jameshi16 commented on chatdownloader/src/metadata/mod.rs
> +        tokio::task::yield_now().await;
question: is yield necessary here?

2024-07-21 16:10 UTC, jameshi16 commented on chatdownloader/src/metrics/mod.rs
> +            mpsc_sender: None,
same blocking comment please

2024-07-21 16:10 UTC, jameshi16 commented on chatdownloader/src/metrics/mod.rs
> +                panic!("No mpsc sender found, did you run get_defaults_and_setup_channels?");
same comment as @owobred

2024-07-21 17:33 UTC, Gaijutsu commented on chatdownloader/src/chatlogprocessor.rs
> +                tokio::task::yield_now().await;
I think youre right, not sure why I added that. It's been removed.

2024-07-21 17:43 UTC, Gaijutsu commented on chatdownloader/src/metadata/mod.rs
> +        tokio::task::yield_now().await;
It probably isn't, I forgot this was process intensive

2024-07-21 20:20 UTC, Gaijutsu commented on chatdownloader/src/leaderboards/leaderboardtrait.rs
> +            .collect();
I blame alcohol :clueless: but I fully agree.

2024-07-21 20:21 UTC, Gaijutsu commented on chatdownloader/src/metadata/special_role.rs
> +    ) -> (String, HashMap<String, MetadataTypes>) {
That's a good idea. I've metadata and metric functions now return MetadataUpdate and MetricUpdate respectively

2024-07-21 20:59 UTC, Gaijutsu commented on chatdownloader/src/metadata/mod.rs
> +            mpsc_sender: None,
That makes a lot of sense. I moved the setup function out of the struct implementation and had it return the struct

2024-07-22 02:01 UTC, Gaijutsu commented
Thank you both for the review. I've done my best to address the requested changes, and clean up the more scuff stuff. 

I'm happy to make any further changes. Thank you! :pray:

2024-07-22 08:10 UTC, jameshi16 requested changes
thank you, looks better now

2024-07-22 08:10 UTC, jameshi16 commented on chatdownloader/src/chatlogprocessor.rs
> +            async move {metadata_processor.run().await; drop(metadata_processor)},
why're we calling `drop()` directly? feels unnecessary

2024-07-22 08:10 UTC, jameshi16 commented on chatdownloader/src/chatlogprocessor.rs
> +        tokio::task::yield_now().await;
why's this outside now? `yield`ing should be done in the for loop

2024-07-22 15:01 UTC, jameshi16 approved these changes
lgtm 👍

2024-07-22 15:02 UTC, merged