#livestream-chat
vanorsigma/neuro-chat-elo pull request #7
Opened 2024-08-01 22:53 UTC by jameshi16

Things to do:
- [ ] Think about whether anything done here makes any sense
- [ ] Badges
- [ ] Maybe want to make copypasta work?

2024-08-12 15:35 UTC, Gaijutsu requested changes
On the whole this looks really good. Just have a few relatively minor changes.

It's probably out of scope for this PR, but I think we should make UserChatPerformances into an enum discriminated by its origin or type. It would make matching easier and reduce code duplication across some of the leaderboards.

2024-08-12 15:35 UTC, Gaijutsu commented on rust/elo/src/leaderboards/nonvips.rs
> +            return None;
See prev

2024-08-12 15:35 UTC, Gaijutsu commented on rust/elo/src/metadata/badges.rs
> +                }
Can this be moved into self.get_metadata_discord like in special_role?

2024-08-12 15:35 UTC, Gaijutsu commented on rust/elo/src/metadata/is_discord_chat.rs
See UserChatPerformances comment

2024-08-12 15:35 UTC, Gaijutsu commented on rust/elo/src/metrics/text.rs
> +                )]),
What do you think about having this matching built into shortcut_for_this_comment_user?

2024-08-12 15:57 UTC, jameshi16 commented on rust/elo/src/leaderboards/leaderboardtrait.rs
> +    fn is_discord_message(&self, performance: &UserChatPerformance) -> bool {
+1 for card

2024-08-15 21:54 UTC, jameshi16 commented on rust/elo/src/leaderboards/nonvips.rs
> +            return None;
This one is a no-can-do, because it'll lead to `if` nesting that I would rather not deal with.

2024-08-15 22:03 UTC, jameshi16 commented on rust/elo/src/metrics/text.rs
> +                )]),
Will have to match twice. Suppose the following:

```rust
fn _shortcut_for_this_message_user(&self, message: &Message, score: f32) -> MetricUpdate {
        let mut map: HashMap<String, f32> = HashMap::new();
        map.insert(match message {
            Message::Twitch(comment) => comment._id.to_string(),
            Message::Discord(msg) => msg.id.to_string(),
        }, score);

        MetricUpdate {
            metric_name: self.get_name(),
            updates: map,
        }
    }
```

Then, this code block will be updated to:
```rust
        self._shortcut_for_this_message_user(
            &message,
            match &message {
                Message::Twitch(comment) => {
                    f32::max(0.0, calculate_score(comment.message.body.len()))
                }
                Message::Discord(msg) => f32::max(0.0, calculate_score(msg.content.len())),
            },
        )
```

to extract the score (the messages have different semantics). One way to fix this would be to have a common message type, but that'll restrict our sources. (In the future, we're likely to have non-chat sources as well)

2024-08-15 22:08 UTC, jameshi16 commented on rust/elo/src/leaderboards/leaderboardtrait.rs
> +    fn is_discord_message(&self, performance: &UserChatPerformance) -> bool {
scratch the card, will have a new design in upcoming revision

2024-08-15 22:12 UTC, Gaijutsu commented on rust/elo/src/leaderboards/nonvips.rs
> +            return None;
I see, nvm then. :+1:

2024-08-16 00:45 UTC, Gaijutsu commented on rust/elo/src/metrics/text.rs
> +                )]),
I see what you mean. In that case, disregard my previous comment, but maybe rename the function to twitch_comment_shortcut or similar (np).

2024-08-16 13:56 UTC, jameshi16 commented
Forgot to commit `chat_origin.rs`, so there was a missing file in the last revision. My bad

2024-08-16 17:47 UTC, Gaijutsu submitted a review, later dismissed
Really nice PR. I especially like those macros, interesting stuff. Will future development be on building them out instead of the enums idea, or are they a stopgap?

The only change isn't breaking at the moment, but will break if the macro is called outside of the `elo` crate. If you make that change, you're good to go as far as I'm concerned.

2024-08-16 17:47 UTC, Gaijutsu commented on rust/elo/src/_types/clptypes.rs
> +macro_rules! declare_messages {
Holy this is awesome, nice 👍

2024-08-16 22:52 UTC, jameshi16 commented
@Gaijutsu one more review to  sanity check

2024-08-16 23:47 UTC, Gaijutsu commented
Good idea for a sanity check. None of the twitch leaderboards have badges lol

2024-08-17 14:34 UTC, jameshi16 commented
Should be fixed now, please check @Gaijutsu

2024-08-18 10:05 UTC, Gaijutsu approved these changes
I can confirm your sanity, feel free to merge :+1:

2024-08-19 12:39 UTC, merged